title: An example of a post
context:
    title: My Blog Post
    published: '2017-01-05'
    contents: |
        Integer quis felis leo. <a href="#">Suspendisse elementum</a>, elit consectetur maximus blandit, lectus leo euismod ipsum, quis efficitur erat augue ut lorem. Duis convallis dictum pellentesque. Quisque eget quam finibus, eleifend odio eget, hendrerit dui. Ut bibendum justo id ex interdum eleifend. Morbi vel magna a lectus dictum dapibus. Aliquam ac tellus posuere risus suscipit vehicula. Sed pharetra fermentum accumsan. Ut malesuada justo mi, at suscipit sapien auctor quis.
        <h3 id="converting-our-markdown-to-html">Converting our Markdown to HTML</h3>
        <p>To convert our markdown file to an HTML file we need to go back to the <code>use()</code> function and invoke the <code>markdown()</code> plugin. There aren't any settings we need to fiddle with right now, just <code>.use(markdown())</code> and we're good to go.</p>
        <pre><code class="lang-js">metalsmith = Metalsmith(__dirname)
            .use(markdown())
            .use(function(files, metalsmith, done) {
                console.log(files);
                console.log(metalsmith);
                done();
            })
            .build(function(err){
                if (err) throw err;
            });
        </code></pre>
        <h2 id="the-many-faces-of-frontend-design">The many faces of Frontend Design</h2>
        <ul>
            <li>UI Developer</li>
            <li>Client Side Developer</li>
            <li>UI Engineer</li>
            <li>Design Engineer</li>
            <li>Designer/Developer</li>
            <li>Prototyper</li>
            <li>Frontend Architect</li>
        </ul>
        <h3 id="if-dante-were-a-developer-he-d-be-a-frontend-designer">If Dante were a developer, he'd be a Frontend Designer</h3>
        <ol>
            <li>Need to be skilled in UX, yet we are not UX developers</li>
            <li>Need to have an eye for design, yet we are not visual designers</li>
            <li>Need to have a mastery with JavaScript, yet we are not JavaScript Developers</li>
            <li>Need to understand the role of our server side code and infrastructure, yet we are neither backend developers or sysops engineers.</li>
        </ol>
    excerpt: Integer quis felis leo. Suspendisse elementum.
