context:
    title: My Blog Post
    published: '2017-01-05'
    contents: <p>Integer quis felis leo. <a href-"#">Suspendisse elementum</a>, elit consectetur maximus blandit, lectus leo euismod ipsum, quis efficitur erat augue ut lorem. Duis convallis dictum pellentesque. Quisque eget quam finibus, eleifend odio eget, hendrerit dui. Ut bibendum justo id ex interdum eleifend. Morbi vel magna a lectus dictum dapibus. Aliquam ac tellus posuere risus suscipit vehicula. Sed pharetra fermentum accumsan. Ut malesuada justo mi, at suscipit sapien auctor quis.</p>
    excerpt: <p>Integer quis felis leo. Suspendisse elementum.</p>
